# Generated by Django 5.2.3 on 2025-06-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
    ]
