# Generated by Django 5.2.3 on 2025-06-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Description',
            new_name='Course',
        ),
    ]
