# Generated by Django 5.2.3 on 2025-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_description_studentmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Course',
            field=models.CharField(max_length=60),
        ),
    ]
