# Generated by Django 5.2.4 on 2025-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='studentId',
            field=models.IntegerField(default=0),
        ),
    ]
